# Generated by Django 5.0.6 on 2024-07-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_predictions_modelprediction_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelname",
            name="featured_usertextinput",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.usertextinput",
            ),
        ),
        migrations.AddField(
            model_name="taskname",
            name="featured_usertextinput",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.usertextinput",
            ),
        ),
        migrations.AlterField(
            model_name="usertextinput",
            name="model_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="userinputs",
                to="api.modelname",
            ),
        ),
        migrations.AlterField(
            model_name="usertextinput",
            name="task_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="userinputs",
                to="api.taskname",
            ),
        ),
    ]
