# Generated by Django 5.0.6 on 2024-07-08 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_modelname_featured_usertextinput_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="defineduser",
            name="featured_userinput",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.usertextinput",
            ),
        ),
        migrations.AlterField(
            model_name="usertextinput",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="userinputs",
                to="api.defineduser",
            ),
        ),
    ]
