# Generated by Django 5.0.6 on 2024-07-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_defineduser_featured_userinput_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelname",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="taskname",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
